### ISSUE TITLE
Label with html content does not render nothing on MacOS

### ISSUE THREAD

**Issue by migueBarrera** [microsoft/dotnet-podcasts#100]
With .NET MAUI RC2

On EpisodeDetailPage. We have this label:
`<Label Style="{StaticResource BodySLabelStyle}"
                       TextType="Html"
                       Text="{Binding Episode.Description}" />`

On MacOS does not render nothing. On Android works fine.

**Comment by migueBarrera** [comment]
@jamesmontemagno

**Comment by jamesmontemagno** [comment]
Hmmmmm. I would file a bug on github.com/dotnet/maui

**Comment by migueBarrera** [comment]
I have done more research. The real issue is that Episode.Detail is not html. Sorry. I will close this issue.
