### ISSUE TITLE
SetTheme causing build failure

### ISSUE THREAD

**Issue by maestro-oc** [microsoft/dotnet-podcasts#121]
The file ListenTogetherComponent.razor in the Blazor folder of the maui project contains the following:

`private async Task UpdateWebThemeAsync()
	{
		var darkModeIsActive = Settings.Theme == AppTheme.Dark;
		await ThemeInterop.SetTheme(darkModeIsActive ? Theme.Dark : Theme.Light);
        

	}`

This is causing the build to fail.  If I set SetTheme to SetThemeAsync all builds correctly.

`private async Task UpdateWebThemeAsync()
	{
		var darkModeIsActive = Settings.Theme == AppTheme.Dark;
		await ThemeInterop.SetThemeAsync(darkModeIsActive ? Theme.Dark : Theme.Light);
        

	}`

**Comment by migueBarrera** [comment]
Fixed in main.
