### ISSUE TITLE
Missing Assets on live running version of the .NET Podcasts app

### ISSUE THREAD

**Issue by devdorn** [microsoft/dotnet-podcasts#14]
I'm visiting the site from Germany and there are some Assets missing in Blob Storage.

Example: https://dotnetpodcasts.azurewebsites.net/discover

![image](https://user-images.githubusercontent.com/399354/146514892-c124e15c-779c-45d3-8ff9-2714e96e698c.png)

**Comment by borjasanes** [comment]
Thanks @devdorn ! Blobs had private access level. It is fixed now.

**Comment by Trigun27** [comment]
I think this problem is happening again

![image](https://user-images.githubusercontent.com/5838703/149996445-b8ab74a1-3d32-4b70-a3c9-0578ae65a5ad.png)

Visited site from Russia

**Comment by jamesmontemagno** [comment]
Yeah, there is just an internal policy that I am working on getting updated so it doesn't flip it back. I have updated it :)

**Comment by jmatthiesen** [comment]
@jamesmontemagno  - this issue is back again. :)

**Comment by jamesmontemagno** [comment]
Just fixed it up :) yeah our policy keeps changing it ;(
