### ISSUE TITLE
Port 5000 already In use on macOS Monterey (Native feature)

### ISSUE THREAD

**Issue by joseasync** [microsoft/dotnet-podcasts#142]
Running the `docker-compose up` to have the services running locally on the docker, I faced the error related to the port 5000 already in use, "Breaking" the setup.

It happens due to a standard feature on the OS (AirPlay Receiver) that is enabled as default and uses this port 5000.
https://developer.apple.com/forums/thread/682332

As it's a native feature, I think would be nice to highlight this on the documentation that is required to disable this flag on the configurations to have the service running on the docker, or maybe we can raise the possibility to have this port changed on the project to work on any supported OS. 

**Reference**: https://developer.apple.com/forums/thread/682332

**Comment by davidbuckleyni** [comment]
You should be able to change the port number from project properties. I think its either under debug or build options this is a trivial thing and one can be fix by simple user changes.

**Comment by davidbuckleyni** [comment]
Please see the first answer here 

https://stackoverflow.com/questions/21202885/how-can-i-change-iis-express-port-for-a-site

I suggest we close this as not really a bug.

**Comment by joseasync** [comment]
Yes, it's not a bug, and easy to make it work. Just raised that for discussion. As it's necessary to change the port on the project for a specific OS, we could add it on the documentation, explaining that it's required (or disable the O.S feature). 
I can do that :)

**Comment by jamesmontemagno** [comment]
We should just change the port for development, let me look real quick.
