### ISSUE TITLE
No back button on Windows to get back to the Discover page

### ISSUE THREAD

**Issue by danroth27** [microsoft/dotnet-podcasts#159]
When running the .NET MAUI (not Blazor) version of .NET Podcasts on Windows, there doesn't appear to be a way to get back to the Discover page after selecting a podcast. There's no back button anywhere like there is on mobile:

![image](https://user-images.githubusercontent.com/1874516/193429003-2167c263-f95c-4ef2-baf3-4bc1ec2be2b8.png)

Clicking on the Discover tab doesn't help.

**Comment by danroth27** [comment]
Aha! Apparently, the back button is there, it just doesn't show up in light mode, but it does in dark mode:

![image](https://user-images.githubusercontent.com/1874516/194424102-a2a83164-ae89-4fff-abdd-c4134924d6da.png)

So this is just a styling issue.

**Comment by Sebosek** [comment]
I guess this relates with https://github.com/dotnet/maui/issues/11127

**Comment by jamesmontemagno** [comment]
I don't see this issue now in .NET 7
