### ISSUE TITLE
Error with kubeEnvironments location

### ISSUE THREAD

**Issue by trevortirrell** [microsoft/dotnet-podcasts#18]
I'm trying to setup the dotnet-podcasts app but I keep getting this error: The subscription is not registered for the resource type 'kubeEnvironments' in the location 'eastus'. Please re-register for this provider in order to have access to this location.

I've tried changing the location in the dotnet-podcasts/deploy/Services/api.deployment.json file, but that doesn't fix it. Originally it was set to 'canadacentral', but that didn't work either.

**Comment by jamesmontemagno** [comment]
Hmmm @nishanil thoughts on this?

**Comment by BaltoAF** [comment]
It seems that KubeEnvironment will be obsolete, and will be replaced by ManagedEnvironments.
Please take a look here : https://github.com/microsoft/azure-container-apps/issues/109

I had this same problem with region North Europe.

**Comment by jamesmontemagno** [comment]
@nishanil  are you able to update this?

**Comment by stephdep** [comment]
Any updates on this ? Thx

**Comment by jamesmontemagno** [comment]
Yes, we now suggest putting everything in East US
