### ISSUE TITLE
Publish to Microsoft Store and GitHub releases

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/dotnet-podcasts#193]
Invites devs to see what the whole thing is like, and whether they can set up releases through and in GitHub as Microsoft envisioned it - MSIX and all.

**Comment by Poopooracoocoo** [comment]
Does https://github.com/microsoft/store-submission support MSIX? @azchohfi

**Comment by azchohfi** [comment]
No, it does not. For MSIX there are other solutions.
If your build is on Azure DevOps, you can use https://marketplace.visualstudio.com/items?itemName=MS-RDX-MRO.windows-store-publish
If your build is on GitHub Actions, you can use https://github.com/marketplace/actions/windows-store-publish

There is also Store Broker, which supports everything related to MSIX publishing to the store, but its setup is harder than the above 2 other options.

**Comment by jamesmontemagno** [comment]
No plans on submitting it into the stores right now, however we do document sample backends that you can use to try out everything by just running the source code.
