### ISSUE TITLE
Delaying Task at JitterHandler

### ISSUE THREAD

**Issue by etcetera33** [microsoft/dotnet-podcasts#209]
JitterHandler waits for some time before performing an action.

```
protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            // Who would do such a thing?!
            // TODO fix this horrible perf leak!
            await Task.Delay(TimeSpan.FromMilliseconds(Random.Shared.NextInt64(50, 500)));
            return await base.SendAsync(request, cancellationToken);
        }
```

Can I be assigned to this one, please?

And if there are any additional details about this (as it feels like) workaround, please, share.

**Comment by jamesmontemagno** [comment]
@baronfel i think added this for a demo..... Should we now remove this or comment it out?

**Comment by etcetera33** [comment]
@baronfel if that is the case, I will gladly comment it out, or better - remove the JitterHandler so that the DelegatingHandlers` SendAsync() is executed without delays.
Waiting for your decision!

cc @jamesmontemagno

**Comment by baronfel** [comment]
Sorry about the delay! Yes, the JitterHandler was introduced so that the OpenTelemetry spans for the calls would be noticable. Without it things happen too dang quick to show in traces! #justdotnetproblems

I think for the _real_ demo app that customers would use, it can be deleted.

**Comment by etcetera33** [comment]
> Sorry about the delay! Yes, the JitterHandler was introduced so that the OpenTelemetry spans for the calls would be noticable. Without it things happen too dang quick to show in traces! #justdotnetproblems
> 
> I think for the _real_ demo app that customers would use, it can be deleted.

No worries!
I`ve posted a PR with the fix, so if you will have a minute, I would really appreciate you looking at it!
