### ISSUE TITLE
Deployment fails when secret password contains "$"

### ISSUE THREAD

**Issue by Soruk** [microsoft/dotnet-podcasts#210]
Hi

I lost 2 hours when deploying to my subscription when using GiHhub action
I put in my secret password '$' sign and the deployment was failing on creating SQL Server  with error
```text
Password validation failed. The password does not meet policy requirements because it is too short.
```
In Yaml files in script tasks the variables should be passed as string (with simple quote ').
When I will have some time I will try to prepare PR that will fix it.

**Comment by jamesmontemagno** [comment]
Is there something in the yaml that can be improved there? Would love a PR if so.

I assume that it met the rest of the policy: https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16#password-complexity

**Comment by Soruk** [comment]
Hi @jamesmontemagno 

Yes my password was working through Azure Portal.

I hope that I will be able to propose some improvements.

BTW, there ware also some inconsistencies between yaml file and bicep file (e.g. new parameter passed from az cli command but not present in ARM template)
