### ISSUE TITLE
The live website is not working

### ISSUE THREAD

**Issue by ngaisteve1** [microsoft/dotnet-podcasts#225]
When I go to https://dotnetpodcasts.azurewebsites.net/, I got these error messages.

Error.
An error occurred while processing your request.
Request ID: 00-5947b58faa5f3049ff0a89b9d77d07ce-7c0aaf04f38c9c6d-00

Development Mode
Swapping to the Development environment displays detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by jamesmontemagno** [comment]
Hmmmmm it seems to be working for me now, let me know if you see it again
