### ISSUE TITLE
[ios] Components podcastImage and epiosdeTitle don't exist in the current context

### ISSUE THREAD

**Issue by kotlarmilos** [microsoft/dotnet-podcasts#239]
## Description

When attempting to publish the app for iOS using .NET version `8.0.100-rtm.23479.1`, the publish fails with:
```
performance/src/scenarios/mauiiospodcast/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(54,9): error CS0103: The name 'podcastImage' does not exist in the current context
performance/src/scenarios/mauiiospodcast/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(55,9): error CS0103: The name 'duration' does not exist in the current context
```
The same issue occured on the CI (https://dev.azure.com/dnceng/internal/_build/results?buildId=2276822&view=logs&j=c04974e3-584c-5152-8f00-7b886e6c86dc&t=1bd054e9-6573-5c14-ef83-f6e1ac550017) with `8.0.100-rc.2` version. These components seems to be defined only when for macOS:
https://github.com/microsoft/dotnet-podcasts/blob/df5d09c15825c761f394766917eae06b0e45e7b4/src/Mobile/Controls/Player.xaml#L45-L67

However, they are referenced here:
https://github.com/microsoft/dotnet-podcasts/blob/df5d09c15825c761f394766917eae06b0e45e7b4/src/Mobile/Controls/Player.xaml.cs#L45-L56

## Repro steps

1. Clone the repository and checkout to `net8.0` branch
2. Run the publish command: `dotnet publish ./dotnet-podcasts/src/Mobile/Microsoft.NetConf2021.Maui.csproj --runtime ios-arm64 --framework net8.0-ios`

/cc: @LoopedBard3 @ivanpovazan

**Comment by LoopedBard3** [comment]
cc @jonathanpeppers

**Comment by ivanpovazan** [comment]
I managed to repro the failure when building with .NET8 rc1 release:
```
/Users/ivan/repos/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(54,9): error CS0103: The name 'podcastImage' does not exist in the current context [/Users/ivan/repos/dotnet-podcasts/src/Mobile/Microsoft.NetConf2021.Maui.csproj::TargetFramework=net8.0-ios]
/Users/ivan/repos/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(55,9): error CS0103: The name 'duration' does not exist in the current context [/Users/ivan/repos/dotnet-podcasts/src/Mobile/Microsoft.NetConf2021.Maui.csproj::TargetFramework=net8.0-ios]
```

- dotnet version: `8.0.100-rc.1.23463.5`
- maui version:
    ```
    maui: Installed Workload Id      Manifest Version                  Installation Source
    --------------------------------------------------------------------------------
    maui                       8.0.0-rc.1.9171/8.0.100-rc.1      SDK 8.0.100-rc.1
    ```

**Comment by ivanpovazan** [comment]
I managed to repro the failure when building with .NET8 rc1 release:
```
/Users/ivan/repos/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(54,9): error CS0103: The name 'podcastImage' does not exist in the current context [/Users/ivan/repos/dotnet-podcasts/src/Mobile/Microsoft.NetConf2021.Maui.csproj::TargetFramework=net8.0-ios]
/Users/ivan/repos/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(55,9): error CS0103: The name 'duration' does not exist in the current context [/Users/ivan/repos/dotnet-podcasts/src/Mobile/Microsoft.NetConf2021.Maui.csproj::TargetFramework=net8.0-ios]
```

- dotnet version: `8.0.100-rc.1.23463.5`
- maui version:
    ```
    maui: Installed Workload Id      Manifest Version                  Installation Source
    --------------------------------------------------------------------------------
    maui                       8.0.0-rc.1.9171/8.0.100-rc.1      SDK 8.0.100-rc.1
    ```

**Comment by ivanpovazan** [comment]
I managed to repro the failure when building with .NET8 rc1 release:
```
/Users/ivan/repos/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(54,9): error CS0103: The name 'podcastImage' does not exist in the current context [/Users/ivan/repos/dotnet-podcasts/src/Mobile/Microsoft.NetConf2021.Maui.csproj::TargetFramework=net8.0-ios]
/Users/ivan/repos/dotnet-podcasts/src/Mobile/Controls/Player.xaml.cs(55,9): error CS0103: The name 'duration' does not exist in the current context [/Users/ivan/repos/dotnet-podcasts/src/Mobile/Microsoft.NetConf2021.Maui.csproj::TargetFramework=net8.0-ios]
```

- dotnet version: `8.0.100-rc.1.23463.5`
- maui version:
    ```
    maui: Installed Workload Id      Manifest Version                  Installation Source
    --------------------------------------------------------------------------------
    maui                       8.0.0-rc.1.9171/8.0.100-rc.1      SDK 8.0.100-rc.1
    ```

**Comment by ivanpovazan** [comment]
Looking more into this, I am not sure how this worked before. 
I assume there was a change in source generators which now takes into account `OnPlatorrm` classes when resolving members defined in XAML.

**Comment by kotlarmilos** [comment]
Thanks for checking out!

> I assume there was a change in source generators which now takes into account `OnPlatorrm` classes when resolving members defined in XAML.

Yes, that sounds reasonable to me. @jonathanpeppers Do you think we should `#ifdef` components based on the platform?

**Comment by jonathanpeppers** [comment]
I bet the behavior changed with: https://github.com/dotnet/maui/pull/5611

It actually seems correct that the `x:Name` fields shouldn't be present on iOS and Android, `#if` seems like the right approach. 👍

**Comment by ivanpovazan** [comment]
Closing as this has been fixed with: https://github.com/microsoft/dotnet-podcasts/commit/9cae3c9343d296ea00eb6e5b83e60f09e8423656

@kotlarmilos could you try to retry the build on dotnet-perf CI ?

**Comment by kotlarmilos** [comment]
Thanks, on it!
