### ISSUE TITLE
Publish to App Stores

### ISSUE THREAD

**Issue by NatElkins** [microsoft/dotnet-podcasts#244]
Hi,

Have you considered publishing this app to the various app stores (App Store, Google Play, etc.)?  It would be really helpful to be able to install and see what a reasonably complex MAUI application feels like with minimal friction.

Thank you!

**Comment by jamesmontemagno** [comment]
We don't have plans to publish the app at this time, but folks can pull it down and run it out of the box without much configuration was our goal.
