### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by AClerbois** [microsoft/dotnet-podcasts#3]
Could you tell me what tools you used to draw the following architectural diagram: 

![https://github.com/microsoft/dotnet-podcasts/raw/main/docs/arch_diagram_podcast.png](https://github.com/microsoft/dotnet-podcasts/raw/main/docs/arch_diagram_podcast.png)

Thank you in advance

Adrien C.

**Comment by jamesmontemagno** [comment]
The Icons are from -> https://docs.microsoft.com/azure/architecture/icons/

@pbousan did you use figma or something else for the diagram itself?

**Comment by pbousan** [comment]
@jamesmontemagno @AClerbois  yes, we use Figma to draw the diagram.

**Comment by AClerbois** [comment]
Thank you @jamesmontemagno & @pbousan for your responses. 

You rocks! 🤘🤘🤘🤘
