### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by hashitha** [microsoft/dotnet-podcasts#33]
What is the best way to handle errors? mainly internet connection drops

Should we use a try catch in the Page and display it on that page or is there a better way?

e.g. `CategoriesPage.razor`
   ```
 private IEnumerable<Category>? categories;
    private PersistingComponentStateSubscription _persistingSubscription;
    private string? _errorMessage ;
    protected override async Task OnInitializedAsync()
    {
        _persistingSubscription = ApplicationState.RegisterOnPersisting(PersistCategories);

        if (!ApplicationState.TryTakeFromJson<IEnumerable<Category>>("categories", out var restored))
        {
            try
            {
                categories = await PodcastService.GetCategories();
            }
            catch (Exception e)
            {
                _errorMessage = e.Message;
            }
            
        }
        else
        {
            categories = restored!;
        }
    }
```

If I run the NetPodsMauiBlazor App without the server running this is what I get.

![image](https://user-images.githubusercontent.com/10569142/150972278-7507ee37-197b-4fba-931d-738a64c5a95d.png)

**Comment by jamesmontemagno** [comment]
I would mostly say the documentation outlines it well: https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-6.0

I will add a new ticket on implement better error handling across all of the apps.

**Comment by hashitha** [comment]
Thanks @jamesmontemagno and @danroth27. This is a great demo and I like that it doesn't rely on bootstrap or any other library like that.
