### ISSUE TITLE
[Bug] App Theme Switch somehow not affect immediately on Shell Background

### ISSUE THREAD

**Issue by shinnthant-lab** [microsoft/dotnet-podcasts#36]
I cloned and just run the app on Windows 10 using visual studio 2022 Preview 3 & MAUI Preview 12. 
It built successfully and managed to be runnable. 
When I tried to switch theme, shell background stuck in old theme, after restarted the app seems showing correct theme.

It's working correctly at MAUI Preview 11 version code base as I remembered.
And also I'm facing the same issue at my new project working on visual studio 2022 Preview 3 & MAUI Preview 12. 

Please see below screen shot for your reference.
![image](https://user-images.githubusercontent.com/54578974/151099759-4892fedb-4fff-4008-a416-ae26eb3cc1b8.png)

With many thanks,

**Comment by jamesmontemagno** [comment]
Yup, this is a new thing. I need to open a bug with the .NET MAUI team. this started with P11.

**Comment by shinnthant-lab** [comment]
Thanks alot bro. this one made me mad in my project until your new video on Youtube.
