### ISSUE TITLE
Error : android:Exported require on IntentFilter

### ISSUE THREAD

**Issue by auriou** [microsoft/dotnet-podcasts#38]
Hello, with Android Emulator, I get this error when launching the Podcasts.DotnetMaui project 

crc64304231ab98fa0dde.MediaPlayerService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

**Comment by jamesmontemagno** [comment]
Good find, i assume this is when running on API 31 emulator... was running on API 30 most of the time ;)

**Comment by jamesmontemagno** [comment]
Fixed up :)
