### ISSUE TITLE
Ios Constructor Error at VS Mac 2022(preview)

### ISSUE THREAD

**Issue by devopsoftware** [microsoft/dotnet-podcasts#39]
IOS Project fails at start with below error at Visual Studio Mac 2022(Preview), while it can build without an issue at Windows 2022(Preview) with remote mac connection. Does Mac 2022 preview not supported yet or any configuration is required for mac builds?

- No parameterless constructor defined for type '...DiscoverPage'

**Comment by jamesmontemagno** [comment]
Visual Studio for Mac 2022 preview doesn't support .NET MAUI fully yet.

**Comment by jamesmontemagno** [comment]
Looks like this is fixed up now.
