### ISSUE TITLE
iOS App Store button doesn't work

### ISSUE THREAD

**Issue by ruffin--** [microsoft/dotnet-podcasts#4]
I'm probably jumping the gun, but the iOS link to download in the App Store is a hash.

https://dotnetpodcasts.azurewebsites.net/
```
<a href="#" title="Download on the App Store">
    <img src="images/download-app_store.png" alt="Download on the App Store" loading="lazy">
</a>
```

Maybe you've got an element selector in some JavaScript somewhere, but clicking just goes to `#`.

Should this app be available?

**Comment by jamesmontemagno** [comment]
We havent' published any of the apps to the stores yet, but it is our plan :)
