### ISSUE TITLE
Enabling Nav bar and using the back button causing a crash

### ISSUE THREAD

**Issue by siddharthsingh89** [microsoft/dotnet-podcasts#43]
I used the Dependency injection style used in the Podcast App for my own test app. Everything works fine but-

After enabling the nav bar using  Shell.NavBarIsVisible="True" in one of the pages and clicking on Back button (to go back ) crashed the App with below exception-

`The specified child already has a parent. You must call removeView() on the child's parent first. `

Is that a known bug in the MAUI Dependency Injection? Any workarounds?
VS 2022 - 17.2.0 Preview 1

**Comment by jamesmontemagno** [comment]
I would probably post an issue over at https://github.com/dotnet/maui if it is an issue there.
