### ISSUE TITLE
The live site has permission issue with Azure storage account.

### ISSUE THREAD

**Issue by StevenTCramer** [microsoft/dotnet-podcasts#50]
409 (Public access is not permitted on this storage account.)

![image](https://user-images.githubusercontent.com/357219/159742621-fb90523f-5830-497a-8f89-1e65621a2fc0.png)

**Comment by jamesmontemagno** [comment]
updated again ;)

**Comment by StevenTCramer** [comment]
@jamesmontemagno  Thanks cool!
