### ISSUE TITLE
Images loaded over HTTP don't show up when running from VS

### ISSUE THREAD

**Issue by danroth27** [microsoft/dotnet-podcasts#63]
If I start the backend by running `docker-compose up` and then run the web app from VS using the Podcasts.Web solution, some of the images don't show up in the podcast player app because by the default VS will launch the site under HTTPS, but some of the podcast images are HTTP URLs:

![image](https://user-images.githubusercontent.com/1874516/163073776-cef567ef-a52a-46f9-be5a-00df4245daf3.png)

**Comment by jamesmontemagno** [comment]
I think we have fixed most if not all of this.
