### ISSUE TITLE
Shell menu items not aligned on MacOS

### ISSUE THREAD

**Issue by migueBarrera** [microsoft/dotnet-podcasts#98]
![Screenshot 2022-04-29 at 12 55 28](https://user-images.githubusercontent.com/21368617/165932059-7b38ebbb-397a-4418-b72a-d9819b63d612.png)

It is possible do anything for this?

@jamesmontemagno

**Comment by jamesmontemagno** [comment]
@pureween @davidortinau  do you both have an example of a nice flyout item layout?

**Comment by antborari** [comment]
@jamesmontemagno @migueBarrera 
Tested on Mac with RC3 and new Maui templates default Shell menu


<img width="795" alt="Screenshot 2022-05-11 at 13 44 42" src="https://user-images.githubusercontent.com/31516548/167842366-de11b7a3-9871-43ed-8ee3-d316a30d9864.png">

**Comment by pulimento** [comment]
Fixed with PR #128. Closing this one
