### ISSUE TITLE
Empty podcast list on MacOS with GridItemsLayout

### ISSUE THREAD

**Issue by migueBarrera** [microsoft/dotnet-podcasts#99]
With .NET MAUI RC2. 
**DiscoverPage**
When launch do not load any item. If you remove GridItemsLayout works fine.

In the future, we port to Flexlayout.

**Comment by migueBarrera** [comment]
I have opened a bug in the maui repository with this issue:
https://github.com/dotnet/maui/issues/6848

**Comment by migueBarrera** [comment]
I created a workaround here: https://github.com/microsoft/dotnet-podcasts/pull/104

**Comment by migueBarrera** [comment]
Some issue with .NET MAUI RC3

**Comment by pulimento** [comment]
Perhaps it'll change when we use FlexLayout

**Comment by jamesmontemagno** [comment]
Closing out as going to re-write some stuff here.
